# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-26 22:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelApp', '0002_auto_20160726_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='image',
            field=models.FileField(null=True, upload_to='TravelApp'),
        ),
    ]
