# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-27 00:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelApp', '0005_auto_20160727_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='image',
            field=models.FileField(null=True, upload_to='media/TravelApp'),
        ),
    ]
