# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-27 01:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelApp', '0007_auto_20160727_0032'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='location',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='season',
            old_name='season',
            new_name='name',
        ),
    ]
