# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-27 14:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('travelApp', '0008_auto_20160727_0117'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='activity',
            new_name='activities',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='place',
            name='season',
        ),
        migrations.RemoveField(
            model_name='place',
            name='title',
        ),
        migrations.AddField(
            model_name='activity',
            name='beach',
            field=models.CharField(default=datetime.datetime(2016, 7, 27, 14, 36, 12, 776374, tzinfo=utc), max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activity',
            name='climbing',
            field=models.CharField(default=datetime.datetime(2016, 7, 27, 14, 36, 21, 200130, tzinfo=utc), max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activity',
            name='hiking',
            field=models.CharField(default=datetime.datetime(2016, 7, 27, 14, 36, 28, 551897, tzinfo=utc), max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='place',
            name='location',
            field=models.CharField(default=datetime.datetime(2016, 7, 27, 14, 36, 33, 559699, tzinfo=utc), max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='place',
            name='travellers',
            field=models.ManyToManyField(to='travelApp.User'),
        ),
    ]
